version: '2'

services:
  consul:
    image: consul
    ports:
      - 8500:8500
    hostname: consulserver
    command: agent -server -bootstrap -ui -client 0.0.0.0
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - $PWD/extra/grafana_db:/var/lib/grafana grafana/grafana
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  hystrix:
    image: mlabouardy/hystrix-dashboard
    ports:
      - 8181:9002
